---
machine:
  rotors:
    left:
      name: 'VII'
      pos: 10
      ring: 1
    middle:
      name: 'V'
      pos: 5
      ring: 2
    right:
      name: 'IV'
      pos: 12
      ring: 3
  reflector: 'B'
  plugboard:
    - 'AG'
    - 'HR'
    - 'YT'
    - 'KI'
    - 'FL'
    - 'WE'
    - 'NM'
    - 'SD'
    - 'OP'
    - 'QJ'

